-- liquibase formatted sql

-- changeset consolidated:01-profiles
CREATE SCHEMA IF NOT EXISTS profiles;

CREATE TABLE profiles.family_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    immutable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version INTEGER DEFAULT 0
);

CREATE TABLE profiles.age_group_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    min_age INTEGER NOT NULL,
    max_age INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version INTEGER DEFAULT 0
);

CREATE TABLE profiles.user (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    enabled BOOLEAN NOT NULL DEFAULT true,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_email ON profiles.user(email);

CREATE TABLE profiles.user_profile (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    photo VARCHAR(255),
    facebook VARCHAR(255),
    mobile_phone VARCHAR(20),
    instagram VARCHAR(255),
    linkedin VARCHAR(255),
    birthdate DATE,
    family_role_id BIGINT,
    age_group_name VARCHAR(50),
    version INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_profile_family_role FOREIGN KEY (family_role_id) REFERENCES profiles.family_roles(id)
);

CREATE INDEX idx_user_profile_mobile_phone ON profiles.user_profile(mobile_phone);

CREATE TABLE profiles.user_preferences (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    show_shopping_widget BOOLEAN NOT NULL DEFAULT true,
    show_coupons_widget BOOLEAN NOT NULL DEFAULT true,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_preferences_user_id ON profiles.user_preferences(user_id);

-- Initial Data for Profiles
INSERT INTO profiles.family_roles (name, immutable) VALUES 
('Mother', TRUE), ('Father', TRUE), ('Son', TRUE), ('Daughter', TRUE);

INSERT INTO profiles.age_group_config (name, min_age, max_age) VALUES 
('Child', 0, 12), ('Teenager', 13, 17), ('Adult', 18, 120);
