-- liquibase formatted sql

-- changeset consolidated:03-recipes
CREATE SCHEMA IF NOT EXISTS recipes;

-- Recipes Table
CREATE TABLE recipes.recipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    servings INTEGER NOT NULL DEFAULT 1,
    source_link TEXT,
    video_link TEXT,
    prep_time_minutes INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipes_created_by FOREIGN KEY (created_by) REFERENCES profiles.user(id),
    CONSTRAINT uk_recipe_name_creator UNIQUE (name, created_by)
);

CREATE INDEX idx_recipes_created_by ON recipes.recipes(created_by);

-- Labels Table
CREATE TABLE recipes.labels (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Recipe Labels Junction Table
CREATE TABLE recipes.recipe_labels (
    recipe_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,

    PRIMARY KEY (recipe_id, label_id),
    CONSTRAINT fk_recipe_labels_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_labels_label FOREIGN KEY (label_id) REFERENCES recipes.labels(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_labels_recipe ON recipes.recipe_labels(recipe_id);
CREATE INDEX idx_recipe_labels_label ON recipes.recipe_labels(label_id);

-- Recipe Photos Table
CREATE TABLE recipes.recipe_photos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    photo_name VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_photos_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_photos_recipe ON recipes.recipe_photos(recipe_id);

-- Nutrients Master Table
CREATE TABLE recipes.nutrients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    unit VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Recipe Ingredients Table
CREATE TABLE recipes.recipe_ingredients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.0,
    unit VARCHAR(20) NOT NULL,
    group_name VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_ingredients_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredients_item FOREIGN KEY (item_id) REFERENCES shopping.shopping_items(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_ingredients_recipe ON recipes.recipe_ingredients(recipe_id);
CREATE INDEX idx_recipe_ingredients_item ON recipes.recipe_ingredients(item_id);
CREATE INDEX idx_recipe_ingredients_recipe_group ON recipes.recipe_ingredients(recipe_id, group_name);

-- Nutrition Entries Table (linked to Master Items)
CREATE TABLE recipes.nutrition_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id BIGINT NOT NULL,
    nutrient_id BIGINT NOT NULL,
    value DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_nutrition_entries_item FOREIGN KEY (item_id) REFERENCES shopping.shopping_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_nutrition_entry_nutrient FOREIGN KEY (nutrient_id) REFERENCES recipes.nutrients(id)
);

CREATE INDEX idx_nutrition_entries_item ON recipes.nutrition_entries(item_id);
CREATE UNIQUE INDEX idx_nutrition_entries_item_nutrient ON recipes.nutrition_entries(item_id, nutrient_id);

-- Recipe Steps Table
CREATE TABLE recipes.recipe_steps (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    instruction TEXT NOT NULL,
    time_minutes INTEGER,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_steps_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_steps_recipe ON recipes.recipe_steps(recipe_id);
CREATE INDEX idx_recipe_steps_order ON recipes.recipe_steps(recipe_id, sort_order);

-- Recipe Comments Table
CREATE TABLE recipes.recipe_comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_comments_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_comments_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_comments_recipe ON recipes.recipe_comments(recipe_id);

-- Recipe Ratings Table
CREATE TABLE recipes.recipe_ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_ratings_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ratings_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT uk_recipe_rating_user UNIQUE (recipe_id, user_id)
);

CREATE INDEX idx_recipe_ratings_recipe ON recipes.recipe_ratings(recipe_id);

-- Initial Nutrient Data
INSERT INTO recipes.nutrients (name, description, unit) VALUES
('Energy', 'Total energy value', 'kcal'),
('Fat', 'Total fat content', 'g'),
('Saturated Fat', 'Saturated fatty acids', 'g'),
('Mono-unsaturated Fat', 'Monounsaturated fatty acids', 'g'),
('Poly-unsaturated Fat', 'Polyunsaturated fatty acids', 'g'),
('Carbohydrate', 'Total carbohydrate content', 'g'),
('Sugars', 'Total sugar content', 'g'),
('Polyols', 'Sugar alcohols', 'g'),
('Starch', 'Starch content', 'g'),
('Fibre', 'Dietary fibre', 'g'),
('Protein', 'Total protein content', 'g'),
('Salt', 'Salt content based on sodium', 'g'),
('Sodium', 'Sodium content', 'mg'),
('Vitamin A', 'Retinol', 'µg'),
('Vitamin C', 'Ascorbic acid', 'mg'),
('Calcium', 'Calcium mineral', 'mg'),
('Iron', 'Iron mineral', 'mg')
ON CONFLICT (name) DO NOTHING;
