-- liquibase formatted sql

-- changeset consolidated:04-meals
CREATE SCHEMA IF NOT EXISTS meals;

-- Meal Times Table
CREATE TABLE meals.meal_times (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Meal Time Schedules Table
CREATE TABLE meals.meal_time_schedules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meal_time_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    start_time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_time_schedule_meal_time FOREIGN KEY (meal_time_id) REFERENCES meals.meal_times(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_time_day UNIQUE (meal_time_id, day_of_week)
);

CREATE INDEX idx_meal_time_schedules_meal_time ON meals.meal_time_schedules(meal_time_id);

-- Meal Plans Table
CREATE TABLE meals.meal_plans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    week_start_date DATE NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Meal Plan Entries Table
CREATE TABLE meals.meal_plan_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_id BIGINT NOT NULL,
    meal_time_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    is_done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_plan_entry_plan FOREIGN KEY (plan_id) REFERENCES meals.meal_plans(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_plan_entry_time FOREIGN KEY (meal_time_id) REFERENCES meals.meal_times(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_plan_entry UNIQUE (plan_id, meal_time_id, day_of_week)
);

CREATE INDEX idx_meal_plan_entries_plan ON meals.meal_plan_entries(plan_id);

-- Meal Plan Entry Recipes Table
CREATE TABLE meals.meal_plan_entry_recipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT, -- Null means for everyone
    multiplier DECIMAL(10,2) NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_entry_recipe_entry FOREIGN KEY (entry_id) REFERENCES meals.meal_plan_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_recipe_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_recipe_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE SET NULL
);

CREATE INDEX idx_entry_recipes_entry ON meals.meal_plan_entry_recipes(entry_id);

-- Meal Plan Votes Table
CREATE TABLE meals.meal_plan_votes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    vote BOOLEAN NOT NULL, -- True = Thumbs Up, False = Thumbs Down
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_plan_votes_entry FOREIGN KEY (entry_id) REFERENCES meals.meal_plan_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_plan_votes_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_plan_vote_user UNIQUE (entry_id, user_id)
);

CREATE INDEX idx_meal_plan_votes_entry ON meals.meal_plan_votes(entry_id);

-- Initial Meal Times and Schedules
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Breakfast', 1);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Lunch', 2);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Afternoon Snack', 3);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Dinner', 4);

-- Breakfast (07:00)
INSERT INTO meals.meal_time_schedules (meal_time_id, day_of_week, start_time) 
SELECT id, d, '07:00:00' FROM meals.meal_times CROSS JOIN generate_series(0,6) AS d WHERE name = 'Breakfast';

-- Lunch (12:00)
INSERT INTO meals.meal_time_schedules (meal_time_id, day_of_week, start_time) 
SELECT id, d, '12:00:00' FROM meals.meal_times CROSS JOIN generate_series(0,6) AS d WHERE name = 'Lunch';

-- Afternoon Snack (15:00)
INSERT INTO meals.meal_time_schedules (meal_time_id, day_of_week, start_time) 
SELECT id, d, '15:00:00' FROM meals.meal_times CROSS JOIN generate_series(0,6) AS d WHERE name = 'Afternoon Snack';

-- Dinner (18:00)
INSERT INTO meals.meal_time_schedules (meal_time_id, day_of_week, start_time) 
SELECT id, d, '18:00:00' FROM meals.meal_times CROSS JOIN generate_series(0,6) AS d WHERE name = 'Dinner';
