--liquibase formatted sql

--changeset jorge:04-initial-recipes-schema
CREATE SCHEMA IF NOT EXISTS recipes;

-- Recipes Table
CREATE TABLE recipes.recipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    servings INTEGER NOT NULL DEFAULT 1,
    source_link TEXT,
    video_link TEXT,
    prep_time_minutes INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipes_created_by FOREIGN KEY (created_by) REFERENCES profiles.user(id)
);

CREATE INDEX idx_recipes_created_by ON recipes.recipes(created_by);
