-- liquibase formatted sql

-- changeset consolidated:05-notifications
CREATE SCHEMA IF NOT EXISTS notifications;

-- Notifications Table
CREATE TABLE notifications.notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipient_id BIGINT NOT NULL,
    sender_id BIGINT,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    link VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_sender FOREIGN KEY (sender_id) REFERENCES profiles.user(id) ON DELETE SET NULL
);

-- Messages Table
CREATE TABLE notifications.messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_recipient FOREIGN KEY (recipient_id) REFERENCES profiles.user(id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_recipient ON notifications.notifications(recipient_id, is_read);
CREATE INDEX idx_messages_recipient ON notifications.messages(recipient_id, is_read);
CREATE INDEX idx_messages_conversation ON notifications.messages(sender_id, recipient_id);
