--liquibase formatted sql

--changeset jorge:05-recipe-photos-and-labels
-- Recipe Photos Table
CREATE TABLE recipes.recipe_photos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    photo_data TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_photos_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE
);

-- Labels Table
CREATE TABLE recipes.labels (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Recipe Labels Junction Table
CREATE TABLE recipes.recipe_labels (
    recipe_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,

    PRIMARY KEY (recipe_id, label_id),
    CONSTRAINT fk_recipe_labels_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_labels_label FOREIGN KEY (label_id) REFERENCES recipes.labels(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_photos_recipe ON recipes.recipe_photos(recipe_id);
CREATE INDEX idx_recipe_labels_recipe ON recipes.recipe_labels(recipe_id);
CREATE INDEX idx_recipe_labels_label ON recipes.recipe_labels(label_id);
