-- Set schema context
SET search_path TO profiles;

-- Create Family Roles table
CREATE TABLE family_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    immutable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version INTEGER DEFAULT 0
);

-- Create Age Group Configuration table
CREATE TABLE age_group_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    min_age INTEGER NOT NULL,
    max_age INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    version INTEGER DEFAULT 0
);

-- Update User Profiles table
ALTER TABLE user_profile
ADD COLUMN birthdate DATE,
ADD COLUMN family_role_id BIGINT,
ADD COLUMN age_group_name VARCHAR(50),
ADD COLUMN version INTEGER DEFAULT 0;

-- Add Foreign Key constraint
ALTER TABLE user_profile
ADD CONSTRAINT fk_user_profile_family_role
FOREIGN KEY (family_role_id) REFERENCES family_roles(id);

-- Insert Immutable Initial Roles
INSERT INTO family_roles (name, immutable) VALUES ('Mother', TRUE);
INSERT INTO family_roles (name, immutable) VALUES ('Father', TRUE);
INSERT INTO family_roles (name, immutable) VALUES ('Son', TRUE);
INSERT INTO family_roles (name, immutable) VALUES ('Daughter', TRUE);

-- Insert Default Age Group Configs
INSERT INTO age_group_config (name, min_age, max_age) VALUES ('Child', 0, 12);
INSERT INTO age_group_config (name, min_age, max_age) VALUES ('Teenager', 13, 17);
INSERT INTO age_group_config (name, min_age, max_age) VALUES ('Adult', 18, 120);
