--liquibase formatted sql

--changeset jorge:06-recipe-ingredients-and-nutrition
-- Recipe Ingredients Table
CREATE TABLE recipes.recipe_ingredients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.0,
    unit VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_ingredients_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredients_item FOREIGN KEY (item_id) REFERENCES shopping.shopping_items(id) ON DELETE CASCADE
);

-- Nutrition Entries Table (linked to Master Items)
CREATE TABLE recipes.nutrition_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id BIGINT NOT NULL,
    nutrient_key VARCHAR(50) NOT NULL,
    value DECIMAL(10,2) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_nutrition_entries_item FOREIGN KEY (item_id) REFERENCES shopping.shopping_items(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_ingredients_recipe ON recipes.recipe_ingredients(recipe_id);
CREATE INDEX idx_recipe_ingredients_item ON recipes.recipe_ingredients(item_id);
CREATE INDEX idx_nutrition_entries_item ON recipes.nutrition_entries(item_id);
CREATE UNIQUE INDEX idx_nutrition_entries_item_nutrient ON recipes.nutrition_entries(item_id, nutrient_key);
