-- liquibase formatted sql

-- changeset jorgemonteiro:07-meal-items
-- Meal Plan Entry Items Table
CREATE TABLE meals.meal_plan_entry_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    user_id BIGINT, -- Null means for everyone
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.0,
    unit VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_entry_item_entry FOREIGN KEY (entry_id) REFERENCES meals.meal_plan_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_item_item FOREIGN KEY (item_id) REFERENCES shopping.shopping_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_item_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE SET NULL
);

CREATE INDEX idx_entry_items_entry ON meals.meal_plan_entry_items(entry_id);
