--liquibase formatted sql

--changeset jorge:07-recipe-steps
-- Recipe Steps Table
CREATE TABLE recipes.recipe_steps (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    instruction TEXT NOT NULL,
    time_minutes INTEGER,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_steps_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_steps_recipe ON recipes.recipe_steps(recipe_id);
CREATE INDEX idx_recipe_steps_order ON recipes.recipe_steps(recipe_id, sort_order);
