--liquibase formatted sql

--changeset jorge:08-recipe-comments-and-ratings
-- Recipe Comments Table
CREATE TABLE recipes.recipe_comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_comments_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_comments_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE
);

-- Recipe Ratings Table
CREATE TABLE recipes.recipe_ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_ratings_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ratings_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT uk_recipe_rating_user UNIQUE (recipe_id, user_id)
);

CREATE INDEX idx_recipe_comments_recipe ON recipes.recipe_comments(recipe_id);
CREATE INDEX idx_recipe_ratings_recipe ON recipes.recipe_ratings(recipe_id);
