--liquibase formatted sql

--changeset jorge:09-initial-meals-schema
CREATE SCHEMA IF NOT EXISTS meals;

-- Meal Times Table
CREATE TABLE meals.meal_times (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Meal Time Schedules Table
CREATE TABLE meals.meal_time_schedules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meal_time_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
    start_time TIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_time_schedule_meal_time FOREIGN KEY (meal_time_id) REFERENCES meals.meal_times(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_time_day UNIQUE (meal_time_id, day_of_week)
);

CREATE INDEX idx_meal_time_schedules_meal_time ON meals.meal_time_schedules(meal_time_id);

-- Seed basic meal times
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Breakfast', 1);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Lunch', 2);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Snack', 3);
INSERT INTO meals.meal_times (name, sort_order) VALUES ('Dinner', 4);
