--liquibase formatted sql

--changeset jorge:10-meal-planning-tables
-- Meal Plans Table
CREATE TABLE meals.meal_plans (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    week_start_date DATE NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Meal Plan Entries Table
CREATE TABLE meals.meal_plan_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_id BIGINT NOT NULL,
    meal_time_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
    is_done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_plan_entry_plan FOREIGN KEY (plan_id) REFERENCES meals.meal_plans(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_plan_entry_time FOREIGN KEY (meal_time_id) REFERENCES meals.meal_times(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_plan_entry UNIQUE (plan_id, meal_time_id, day_of_week)
);

-- Meal Plan Entry Recipes Table
CREATE TABLE meals.meal_plan_entry_recipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    user_id BIGINT, -- Null means for everyone
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_entry_recipe_entry FOREIGN KEY (entry_id) REFERENCES meals.meal_plan_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_recipe_recipe FOREIGN KEY (recipe_id) REFERENCES recipes.recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_recipe_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE SET NULL
);

CREATE INDEX idx_meal_plan_entries_plan ON meals.meal_plan_entries(plan_id);
CREATE INDEX idx_entry_recipes_entry ON meals.meal_plan_entry_recipes(entry_id);
