--liquibase formatted sql

--changeset jorge:12-meal-plan-votes
-- Meal Plan Votes Table
CREATE TABLE meals.meal_plan_votes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    vote BOOLEAN NOT NULL, -- True = Thumbs Up, False = Thumbs Down
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_meal_plan_votes_entry FOREIGN KEY (entry_id) REFERENCES meals.meal_plan_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_plan_votes_user FOREIGN KEY (user_id) REFERENCES profiles.user(id) ON DELETE CASCADE,
    CONSTRAINT uk_meal_plan_vote_user UNIQUE (entry_id, user_id)
);

CREATE INDEX idx_meal_plan_votes_entry ON meals.meal_plan_votes(entry_id);
