--liquibase formatted sql

--changeset jorge:13-media-photos-schema
CREATE SCHEMA IF NOT EXISTS media;

-- Central Photos Table
CREATE TABLE media.photos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL, -- profile, recipe, item, store, etc.
    extension VARCHAR(10) NOT NULL, -- png, jpg, svg, etc.
    content_type VARCHAR(100) NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_photos_type ON media.photos(type);
CREATE INDEX idx_photos_name ON media.photos(name);
