--liquibase formatted sql

--changeset jorge:16-normalize-nutrients
-- 1. Create Nutrients table
CREATE TABLE recipes.nutrients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    unit VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- 2. Seed common European nutrients
INSERT INTO recipes.nutrients (name, description, unit) VALUES
('Energy', 'Total energy value', 'kcal'),
('Fat', 'Total fat content', 'g'),
('Saturated Fat', 'Saturated fatty acids', 'g'),
('Mono-unsaturated Fat', 'Monounsaturated fatty acids', 'g'),
('Poly-unsaturated Fat', 'Polyunsaturated fatty acids', 'g'),
('Carbohydrate', 'Total carbohydrate content', 'g'),
('Sugars', 'Total sugar content', 'g'),
('Polyols', 'Sugar alcohols', 'g'),
('Starch', 'Starch content', 'g'),
('Fibre', 'Dietary fibre', 'g'),
('Protein', 'Total protein content', 'g'),
('Salt', 'Salt content based on sodium', 'g'),
('Sodium', 'Sodium content', 'mg'),
('Vitamin A', 'Retinol', 'µg'),
('Vitamin C', 'Ascorbic acid', 'mg'),
('Calcium', 'Calcium mineral', 'mg'),
('Iron', 'Iron mineral', 'mg')
ON CONFLICT (name) DO NOTHING;

-- 3. Prepare nutrition_entries for migration
ALTER TABLE recipes.nutrition_entries ADD COLUMN nutrient_id BIGINT;

-- 4. Map existing entries to new IDs (matching by name/key)
UPDATE recipes.nutrition_entries ne
SET nutrient_id = n.id
FROM recipes.nutrients n
WHERE LOWER(ne.nutrient_key) = LOWER(n.name);

-- 5. For keys that didn't exist in seed, create them dynamically to avoid data loss
INSERT INTO recipes.nutrients (name, unit)
SELECT DISTINCT nutrient_key, unit 
FROM recipes.nutrition_entries 
WHERE nutrient_id IS NULL;

-- 6. Re-run mapping for newly created nutrients
UPDATE recipes.nutrition_entries ne
SET nutrient_id = n.id
FROM recipes.nutrients n
WHERE LOWER(ne.nutrient_key) = LOWER(n.name) AND ne.nutrient_id IS NULL;

-- 7. Apply constraints and cleanup
ALTER TABLE recipes.nutrition_entries ALTER COLUMN nutrient_id SET NOT NULL;
ALTER TABLE recipes.nutrition_entries ADD CONSTRAINT fk_nutrition_entry_nutrient FOREIGN KEY (nutrient_id) REFERENCES recipes.nutrients(id);

-- Drop redundant columns
ALTER TABLE recipes.nutrition_entries DROP COLUMN nutrient_key;
ALTER TABLE recipes.nutrition_entries DROP COLUMN unit;

-- Re-create the unique index
DROP INDEX IF EXISTS recipes.idx_nutrition_entries_item_nutrient;
CREATE UNIQUE INDEX idx_nutrition_entries_item_nutrient ON recipes.nutrition_entries(item_id, nutrient_id);
